spring:
  application:
    name: api-gateway
  security:
    oauth2:
          resourceserver:
            jwt:
              issuer-uri: http://keycloak:8080/realms/ticketing
keycloak:
  auth:
    jwk-set-uri: http://keycloak:8080/realms/ticketing/protocol/openid-connect/certs

management:
  health:
    circuitbreakers:
      enabled: true

  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers

# Resilience4j config
resilience4j:
  circuitbreaker:
    instances:
      inventory-service-cb:
        sliding-window-size: 10           # 10 request terakhir dipantau
        failure-rate-threshold: 50        # kalau 50% gagal → OPEN
        wait-duration-in-open-state: 10s  # tunggu 10s sebelum coba lagi
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
      booking-service-cb:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

  timelimiter:
    instances:
      inventory-service-cb:
        timeout-duration: 3s  # request timeout
      booking-service-cb:
        timeout-duration: 3s

security:
  excluded:
    urls: /swagger-ui.html,/swagger-ui/**,/docs/**,/v3/api-docs/**,/actuator/**,/fallback/**

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Inventory Service
        url: /docs/inventoryservice/v3/api-docs
      - name: Booking Service
        url: /docs/bookingservice/v3/api-docs
  api-docs:
    path: /v3/api-docs